name: Release

on:
  push:
    tags:
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]'
      - '[0-9][0-9]?.[0-9][0-9].[0-9][0-9]-alpha-[0-9]+'

jobs:
  
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v1
      - name: Package (release)
        uses: arkayenro/packager@v2
